version: "3.8"

services:
  celery:
    build:
        context: .
        dockerfile: ./docker/dockerfile.celery
    command: celery -A celery_app worker -B -l info
    env_file: .env

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t78
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local