version: "3.7"

services:
    db:
        image: postgres:12

        environment:
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
            - 5432:5432
        env_file:
            - .env
        volumes:
            - db-data:/var/lib/postgresql/data/pgdata
    redis:
        image: redis
        command: redis-server
        ports:
            - "6379:6379"

volumes:
    db-data:
