version: "3.7"

services:
    db:
        image: postgres:12

        environment:
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
            - 5432:5432
        env_file:
            - .env
        volumes:
            - db-data:/var/lib/postgresql/data/pgdata
    redis:
        image: redis
        command: redis-server
        ports:
            - "6379:6379"

    worker:
        build:
            context: .
            dockerfile: ./docker/dockerfile.celery
        env_file:
            - .env
        depends_on:
            - db
        extra_hosts:
            host.docker.internal: host-gateway

    flower:
        image: mher/flower
        environment:
            - CELERY_BROKER_URL=redis://:eYVX7EwVmmxKPCDmwMtyKVge8oLd2t78@0.tcp.sa.ngrok.io:14113
            - FLOWER_PORT=5555
        ports:
            - 8888:8888

volumes:
    db-data:
