"""criando tabela auto tasks

Revision ID: 1950285f49da
Revises: 955dd11f04ef
Create Date: 2022-03-25 15:39:12.409349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1950285f49da'
down_revision = '955dd11f04ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('post_instagram', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auto_tasks')
    # ### end Alembic commands ###
