"""first

Revision ID: 1add4e92a1e3
Revises: 
Create Date: 2021-10-26 14:46:22.402284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1add4e92a1e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_slip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('url_s3', sa.String(), nullable=False),
    sa.Column('cpf_cnpj', sa.String(), nullable=False),
    sa.Column('cod_acordo', sa.BigInteger(), nullable=True),
    sa.Column('qtd_parcelas', sa.Integer(), nullable=True),
    sa.Column('parcela_numero', sa.Integer(), nullable=True),
    sa.Column('contratos_vinculados', sa.String(), nullable=True),
    sa.Column('data_vencimento', sa.DateTime(), nullable=True),
    sa.Column('data_validade', sa.DateTime(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('carteira', sa.String(), nullable=True),
    sa.Column('crm', sa.String(), nullable=True),
    sa.Column('cod_convenio_mcob', sa.String(), nullable=True),
    sa.Column('linha_digitavel', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cod_acordo', 'cpf_cnpj', name='uq_codacordo_cpfcnpj')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_slip')
    # ### end Alembic commands ###
