"""twitch clips not null

Revision ID: 2617b13bf797
Revises: 3a368098ebb0
Create Date: 2022-05-19 15:03:41.187768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2617b13bf797'
down_revision = '3a368098ebb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kraken', 'twitch_clips_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kraken', 'twitch_clips_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
