"""ajusta-relacoes

Revision ID: 2dd28f036bf8
Revises: 53f87287e8a6
Create Date: 2022-04-20 14:43:05.701636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dd28f036bf8'
down_revision = '53f87287e8a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
