"""unificando clips

Revision ID: 2eb951d99504
Revises: 2617b13bf797
Create Date: 2022-05-20 10:05:06.571678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2eb951d99504'
down_revision = '2617b13bf797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kraken_clips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('clip_name', sa.String(), nullable=False),
    sa.Column('clip_id', sa.String(), nullable=False),
    sa.Column('clip_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # op.drop_table('twitch_clips')
    # op.drop_table('youtube_clips')
    op.add_column('kraken', sa.Column('kraken_clips_id', sa.Integer(), nullable=True))
    op.drop_constraint('kraken_youtube_clips_id_fkey', 'kraken', type_='foreignkey')
    op.drop_constraint('kraken_twitch_clips_id_fkey', 'kraken', type_='foreignkey')
    op.create_foreign_key(None, 'kraken', 'kraken_clips', ['kraken_clips_id'], ['id'])
    op.drop_column('kraken', 'youtube_clips_id')
    op.drop_column('kraken', 'twitch_clips_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kraken', sa.Column('twitch_clips_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('kraken', sa.Column('youtube_clips_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'kraken', type_='foreignkey')
    op.create_foreign_key('kraken_twitch_clips_id_fkey', 'kraken', 'twitch_clips', ['twitch_clips_id'], ['id'])
    op.create_foreign_key('kraken_youtube_clips_id_fkey', 'kraken', 'youtube_clips', ['youtube_clips_id'], ['id'])
    op.drop_column('kraken', 'kraken_clips_id')
    op.create_table('youtube_clips',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('clip_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('clip_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('clip_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='youtube_clips_pkey')
    )
    op.create_table('twitch_clips',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('clip_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('clip_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('clip_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='twitch_clips_pkey')
    )
    op.drop_table('kraken_clips')
    # ### end Alembic commands ###
