"""relation-foreign

Revision ID: 3235478771c9
Revises: d55a75d7edbe
Create Date: 2022-04-20 14:30:37.530426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3235478771c9'
down_revision = 'd55a75d7edbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_messages', sa.Column('twitter_tasks_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'twitter_messages', 'twitter_tasks', ['twitter_tasks_id'], ['id'])
    op.add_column('twitter_tasks', sa.Column('twitter_messages_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'twitter_tasks', 'twitter_messages', ['twitter_messages_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'twitter_tasks', type_='foreignkey')
    op.drop_column('twitter_tasks', 'twitter_messages_id')
    op.drop_constraint(None, 'twitter_messages', type_='foreignkey')
    op.drop_column('twitter_messages', 'twitter_tasks_id')
    # ### end Alembic commands ###
