"""instagram-tasks

Revision ID: 3647b012ac78
Revises: 9d81eb09c5a4
Create Date: 2022-04-26 14:30:09.568428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3647b012ac78'
down_revision = '9d81eb09c5a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instagram_follow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('instagram_handle', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instagram_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('use_same_db', sa.Boolean(), nullable=True),
    sa.Column('use_same_db_instagram_handle', sa.String(), nullable=True),
    sa.Column('instagram_handle', sa.String(), nullable=False),
    sa.Column('activated', sa.Boolean(), nullable=False),
    sa.Column('instagram_follow_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['instagram_follow_id'], ['instagram_follow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instagram_tasks')
    op.drop_table('instagram_follow')
    # ### end Alembic commands ###
