"""inserindo id

Revision ID: 36aefd78a146
Revises: 4ed178e23998
Create Date: 2022-04-22 10:39:47.350721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36aefd78a146'
down_revision = '4ed178e23998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
