"""kraken-head

Revision ID: 3a368098ebb0
Revises: 5c5ea4396771
Create Date: 2022-05-19 14:26:23.224751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a368098ebb0'
down_revision = '5c5ea4396771'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kraken', sa.Column('kraken_head', sa.String(), server_default='TWITCH', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kraken', 'kraken_head')
    # ### end Alembic commands ###
