"""follow id

Revision ID: 474a5bd29a56
Revises: 36aefd78a146
Create Date: 2022-04-22 10:50:00.651212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '474a5bd29a56'
down_revision = '36aefd78a146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_tasks', sa.Column('twitter_follow_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'twitter_tasks', 'twitter_follow', ['twitter_follow_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'twitter_tasks', type_='foreignkey')
    op.drop_column('twitter_tasks', 'twitter_follow_id')
    # ### end Alembic commands ###
