"""removendo relation

Revision ID: 4ed178e23998
Revises: af3ee8c733db
Create Date: 2022-04-22 10:37:37.832237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ed178e23998'
down_revision = 'af3ee8c733db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
