"""remove-foreign

Revision ID: 53f87287e8a6
Revises: fdfdf4cc9f44
Create Date: 2022-04-20 14:40:01.615967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53f87287e8a6'
down_revision = 'fdfdf4cc9f44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('twitter_messages_twitter_tasks_id_fkey', 'twitter_messages', type_='foreignkey')
    op.drop_column('twitter_messages', 'twitter_tasks_id')
    op.add_column('twitter_tasks', sa.Column('twitter_messages_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'twitter_tasks', 'twitter_messages', ['twitter_messages_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'twitter_tasks', type_='foreignkey')
    op.drop_column('twitter_tasks', 'twitter_messages_id')
    op.add_column('twitter_messages', sa.Column('twitter_tasks_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('twitter_messages_twitter_tasks_id_fkey', 'twitter_messages', 'twitter_tasks', ['twitter_tasks_id'], ['id'])
    # ### end Alembic commands ###
