"""removing kraken head from kraken

Revision ID: 6dd13e2b0825
Revises: 99f127633022
Create Date: 2022-09-09 11:59:34.100900

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6dd13e2b0825'
down_revision = '99f127633022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kraken', 'kraken_head')
    op.add_column('kraken_clips', sa.Column('kraken_head', sa.String(), server_default='TWITCH', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kraken_clips', 'kraken_head')
    op.add_column('kraken', sa.Column('kraken_head', sa.VARCHAR(), server_default=sa.text("'TWITCH'::character varying"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
