"""unllable true

Revision ID: 80fa53e869ed
Revises: 474a5bd29a56
Create Date: 2022-04-22 10:51:39.660308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80fa53e869ed'
down_revision = '474a5bd29a56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('twitter_tasks', 'twitter_messages_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('twitter_tasks', 'twitter_follow_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('twitter_tasks', 'twitter_follow_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('twitter_tasks', 'twitter_messages_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
