"""tabela-params-auto-tasks

Revision ID: 91f0ef7be2cf
Revises: 0009d6dcd91f
Create Date: 2022-04-02 17:08:07.304537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91f0ef7be2cf'
down_revision = '0009d6dcd91f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('activated', sa.Boolean(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('bool_value', sa.Boolean(), nullable=False),
    sa.Column('int_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('auto_tasks', 'post_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('auto_tasks', 'twitch_creator_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auto_tasks', 'twitch_creator_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('auto_tasks', 'post_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('parameters')
    # ### end Alembic commands ###
