"""ajustando relation

Revision ID: 955dd11f04ef
Revises: 762b8f6f82a0
Create Date: 2022-03-25 13:47:29.138228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '955dd11f04ef'
down_revision = '762b8f6f82a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kraken', 'twitch_clips_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kraken', 'twitch_clips_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
