"""criando table twitch clips

Revision ID: a9e7e8f4007b
Revises: 4972fa40cdad
Create Date: 2022-03-25 09:43:53.868574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9e7e8f4007b'
down_revision = '4972fa40cdad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitch_clips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('clip_id', sa.String(), nullable=True),
    sa.Column('clip_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('kraken', sa.Column('twitch_clips_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'kraken', 'twitch_clips', ['twitch_clips_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'kraken', type_='foreignkey')
    op.drop_column('kraken', 'twitch_clips_id')
    op.drop_table('twitch_clips')
    # ### end Alembic commands ###
