"""testa-relation 

Revision ID: af3ee8c733db
Revises: 2dd28f036bf8
Create Date: 2022-04-20 15:57:43.791768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af3ee8c733db'
down_revision = '2dd28f036bf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('twitter_tasks', 'twitter_messages_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('twitter_tasks', 'twitter_messages_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
