"""thumbnail column

Revision ID: bafbc4f36f45
Revises: 6dd13e2b0825
Create Date: 2022-09-09 14:50:57.971062

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bafbc4f36f45'
down_revision = '6dd13e2b0825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kraken_clips', sa.Column('thumbnail', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kraken_clips', 'thumbnail')
    # ### end Alembic commands ###
