"""column status

Revision ID: cef2e1c0ca81
Revises: 1add4e92a1e3
Create Date: 2022-03-22 16:30:19.025933

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cef2e1c0ca81'
down_revision = '1add4e92a1e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('clip_url', sa.String(), nullable=True),
    sa.Column('post_status', sa.String(), nullable=False),
    sa.Column('kraken_hand', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('bank_slip')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_slip',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('url_s3', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cpf_cnpj', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cod_acordo', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('qtd_parcelas', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('parcela_numero', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('contratos_vinculados', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('data_vencimento', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('data_validade', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('valor', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('carteira', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('crm', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cod_convenio_mcob', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('linha_digitavel', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='bank_slip_pkey'),
    sa.UniqueConstraint('cod_acordo', 'cpf_cnpj', name='uq_codacordo_cpfcnpj')
    )
    op.drop_table('twitch')
    # ### end Alembic commands ###
