"""modificando tabela tasks

Revision ID: d55a75d7edbe
Revises: 6e9f6707d408
Create Date: 2022-04-20 13:27:27.804366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd55a75d7edbe'
down_revision = '6e9f6707d408'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_follow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('twitter_handle', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('twitter_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('twitter_handle', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('result_type', sa.String(), server_default='mixed', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('twitter_messages')
    op.drop_table('twitter_follow')
    # ### end Alembic commands ###
