"""column is trending

Revision ID: e5c5c68482e1
Revises: 2eb951d99504
Create Date: 2022-06-01 15:09:23.032349

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e5c5c68482e1'
down_revision = '2eb951d99504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_tasks', sa.Column('is_trending_user', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitter_tasks', 'is_trending_user')
    # ### end Alembic commands ###
