"""use-same-db

Revision ID: f43deb4c9a79
Revises: 7ede91d80f10
Create Date: 2022-04-06 21:01:33.608897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f43deb4c9a79'
down_revision = '7ede91d80f10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_tasks', sa.Column('use_same_db', sa.Boolean(), nullable=True))
    op.add_column('twitter_tasks', sa.Column('use_same_db_twitter_handle', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitter_tasks', 'use_same_db_twitter_handle')
    op.drop_column('twitter_tasks', 'use_same_db')
    # ### end Alembic commands ###
