"""relation-foreign-ajuste

Revision ID: fdfdf4cc9f44
Revises: 3235478771c9
Create Date: 2022-04-20 14:32:59.550786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdfdf4cc9f44'
down_revision = '3235478771c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('twitter_tasks_twitter_messages_id_fkey', 'twitter_tasks', type_='foreignkey')
    op.drop_column('twitter_tasks', 'twitter_messages_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_tasks', sa.Column('twitter_messages_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('twitter_tasks_twitter_messages_id_fkey', 'twitter_tasks', 'twitter_messages', ['twitter_messages_id'], ['id'])
    # ### end Alembic commands ###
